package com.acdiorr.buildpilot.service.impl;

import com.acdiorr.buildpilot.entity.Project;
import com.acdiorr.buildpilot.entity.Quotation;
import com.acdiorr.buildpilot.exception.QuotationNotFoundException;
import com.acdiorr.buildpilot.repository.ProjectRepository;
import com.acdiorr.buildpilot.repository.QuotationRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class QuotationPdfServiceImplTest {

    @Mock
    private ProjectRepository projectRepository;

    @Mock
    private QuotationRepository quotationRepository;

    @InjectMocks
    private QuotationPdfServiceImpl quotationPdfService;

    @Test
    void generateQuotationPdf_shouldReturnPdfBytes() {
        Long projectId = 1L;

        Project project = Project.builder()
                .id(projectId)
                .projectName("Casa Primavera")
                .clientName("John Carter")
                .constructionType("Residential")
                .address("123 Main St")
                .description("Two-story home")
                .creationDate(LocalDate.of(2026, 4, 25))
                .build();

        Quotation quotation = Quotation.builder()
                .id(7L)
                .project(project)
                .materialCost(new BigDecimal("1500.25"))
                .laborCost(new BigDecimal("800.00"))
                .indirectCost(new BigDecimal("120.50"))
                .profitMargin(new BigDecimal("15.00"))
                .subtotal(new BigDecimal("2420.75"))
                .totalCost(new BigDecimal("2783.86"))
                .notes("Valid for 30 days")
                .build();

        when(projectRepository.findById(projectId)).thenReturn(Optional.of(project));
        when(quotationRepository.findByProjectId(projectId)).thenReturn(Optional.of(quotation));

        byte[] pdfBytes = quotationPdfService.generateQuotationPdf(projectId);

        assertTrue(pdfBytes.length > 100, "PDF should not be empty");
        String header = new String(pdfBytes, 0, 4);
        assertTrue(header.startsWith("%PDF"), "Generated bytes must be a valid PDF header");
    }

    @Test
    void generateQuotationPdf_shouldThrowWhenQuotationMissing() {
        Long projectId = 2L;
        Project project = Project.builder().id(projectId).projectName("No Quote Project").build();

        when(projectRepository.findById(projectId)).thenReturn(Optional.of(project));
        when(quotationRepository.findByProjectId(projectId)).thenReturn(Optional.empty());

        assertThrows(QuotationNotFoundException.class,
                () -> quotationPdfService.generateQuotationPdf(projectId));
    }
}

